name: terraform

on:
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/terraform*.yml"
  push:
    branches: [main]
    paths:
      - "terraform/**"
      - ".github/workflows/terraform*.yml"

permissions:
  contents: read
  pull-requests: write

jobs:
  vpc:
    uses: ./.github/workflows/terraform-module.yml
    with:
      module: vpc
    secrets: inherit

  eks:
    needs: vpc
    uses: ./.github/workflows/terraform-module.yml
    with:
      module: eks
    secrets: inherit

  atlantis:
    needs: eks
    uses: ./.github/workflows/terraform-module.yml
    with:
      module: atlantis
    secrets: inherit
